version: '3.6'

x-project-name: &project-name ${COMPOSE_PROJECT_NAME:-projectx}

services:
  db:
    image: postgis/postgis:14-3.3-alpine
    container_name: ${COMPOSE_PROJECT_NAME:-projectx}-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - "com.*project-name.service=database"

  temporal:
    image: temporalio/auto-setup:1.22.2
    container_name: ${COMPOSE_PROJECT_NAME:-projectx}-temporal
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB=postgresql
      - DB_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PWD=${POSTGRES_PASSWORD}
      - POSTGRES_SEEDS=db
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    volumes:
      - ./temporal-dynamicconfig:/etc/temporal/config/dynamicconfig
    networks:
      - backend
    ports:
      - "${TEMPORAL_PORT:-7233}:7233"
    labels:
      - "com.*project-name.service=temporal"
    entrypoint: bash -c "chmod +x /etc/temporal/config/dynamicconfig/entrypoint.sh && /etc/temporal/config/dynamicconfig/entrypoint.sh && exec /bin/bash"

  temporal-admin-tools:
    image: temporalio/admin-tools:1.22.2
    container_name: ${COMPOSE_PROJECT_NAME:-projectx}-temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:${TEMPORAL_PORT:-7233}
      - TEMPORAL_CLI_ADDRESS=temporal:${TEMPORAL_PORT:-7233}
    networks:
      - backend
    stdin_open: true
    tty: true
    labels:
      - "com.*project-name.service=temporal-admin-tools"

  temporal-ui:
    image: temporalio/ui:2.21.3
    container_name: ${COMPOSE_PROJECT_NAME:-projectx}-temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:${TEMPORAL_PORT:-7233}
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    networks:
      - backend
    ports:
      - "${TEMPORAL_UI_PORT:-8080}:8080"
    labels:
      - "com.*project-name.service=temporal-ui"
    expose:
      - "${TEMPORAL_UI_PORT:-8080}"

  # PROJECTX SERVICES

networks:
  backend:
    name: ${COMPOSE_PROJECT_NAME:-projectx}-network

volumes:
  postgres_data:
    name: ${COMPOSE_PROJECT_NAME:-projectx}-postgres-data