version: '3.6'

x-project-name: &project-name ${COMPOSE_PROJECT_NAME:-projectx}

# Define common service settings to reduce duplication
x-service-common: &service-common
  env_file: .env
  networks:
    - default
  depends_on:
    db:
      condition: service_healthy
    temporal:
      condition: service_started
  environment:
    - NX_DISABLE_DB=true
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - .:/app
    - /app/libs/frontend
    - /app/node_modules

services:
  db:
    image: postgis/postgis:17-3.5
    container_name: ${COMPOSE_PROJECT_NAME:-projectx}-db
    restart: always
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata # Explicit PGDATA path
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 2s # Added start period
    labels:
      - "com.*project-name.service=database"
    expose:
      - "${POSTGRES_PORT:-5432}"
    tmpfs:
      - /tmp
      - /run
      - /run/postgresql

  temporal:
    image: temporalio/auto-setup:1.26.2
    container_name: ${COMPOSE_PROJECT_NAME:-projectx}-temporal
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB=postgres12
      - DB_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PWD=${POSTGRES_PASSWORD}
      - POSTGRES_SEEDS=db
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    volumes:
      - ./deployment/config/dynamicconfig:/etc/temporal/config/dynamicconfig
    ports:
      - "${TEMPORAL_PORT:-7233}:7233"
    labels:
      - "com.*project-name.service=temporal"
    expose:
      - "${TEMPORAL_PORT:-7233}"

  temporal-admin-tools:
    image: temporalio/admin-tools:1.26.2-tctl-1.18.1-cli-1.2.0
    container_name: ${COMPOSE_PROJECT_NAME:-projectx}-temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:${TEMPORAL_PORT:-7233}
      - TEMPORAL_CLI_ADDRESS=temporal:${TEMPORAL_PORT:-7233}
      - TEMPORAL_CLI_SHOW_STACKS=1
    stdin_open: true
    tty: true
    labels:
      - "com.*project-name.service=temporal-admin-tools"
    volumes:
      - ./deployment/scripts/search-attributes.sh:/etc/temporal/entrypoint.sh
    entrypoint: >
      /bin/sh -c "
      chmod +x /etc/temporal/entrypoint.sh &&
      /etc/temporal/entrypoint.sh &&
      exec /bin/bash
      "

  temporal-ui:
    image: temporalio/ui:2.34.0
    container_name: ${COMPOSE_PROJECT_NAME:-projectx}-temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:${TEMPORAL_PORT:-7233}
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    ports:
      - "${TEMPORAL_UI_PORT:-8080}:8080"
    labels:
      - "com.*project-name.service=temporal-ui"
    expose:
      - "${TEMPORAL_UI_PORT:-8080}"

  # PROJECTX SERVICES
  auth:
    <<: *service-common
    container_name: auth
    command: >
      bash -c "
      npm run prisma:generate &&
      npm run prisma:migrate &&
      npx nx reset &&
      npm run dev:auth
      "
    ports:
      - "${AUTH_PORT:-8081}:${AUTH_PORT:-8081}"
      - "9229:9229"

  order:
    <<: *service-common
    container_name: order
    command: >
      bash -c "
      npm run prisma:generate &&
      npm run prisma:migrate &&
      npx nx reset &&
      npm run dev:order
      "
    ports:
      - "${ORDER_PORT:-8082}:${ORDER_PORT:-8082}"
      - "9230:9230"

  product:
    <<: *service-common
    container_name: product
    command: >
      bash -c "
      npm run prisma:generate &&
      npm run prisma:migrate &&
      npx nx reset &&
      npm run dev:product
      "
    ports:
      - "${PRODUCT_PORT:-8083}:${PRODUCT_PORT:-8083}"
      - "9231:9231"

  ngrok-order:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "http://host.docker.internal:${ORDER_PORT:-8082}"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME:-projectx}-network
    driver: bridge

volumes:
  postgres_data:
    name: ${COMPOSE_PROJECT_NAME:-projectx}-postgres-data